// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: schema/v1/records.proto

package schemav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Priority orders the sync drain. Higher value drains first.
type Priority int32

const (
	Priority_PRIORITY_UNSPECIFIED Priority = 0
	Priority_PRIORITY_METRIC      Priority = 1
	Priority_PRIORITY_EVENT       Priority = 2
	Priority_PRIORITY_ACTION      Priority = 3
	Priority_PRIORITY_INCIDENT    Priority = 4
)

// Enum value maps for Priority.
var (
	Priority_name = map[int32]string{
		0: "PRIORITY_UNSPECIFIED",
		1: "PRIORITY_METRIC",
		2: "PRIORITY_EVENT",
		3: "PRIORITY_ACTION",
		4: "PRIORITY_INCIDENT",
	}
	Priority_value = map[string]int32{
		"PRIORITY_UNSPECIFIED": 0,
		"PRIORITY_METRIC":      1,
		"PRIORITY_EVENT":       2,
		"PRIORITY_ACTION":      3,
		"PRIORITY_INCIDENT":    4,
	}
)

func (x Priority) Enum() *Priority {
	p := new(Priority)
	*p = x
	return p
}

func (x Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_schema_v1_records_proto_enumTypes[0].Descriptor()
}

func (Priority) Type() protoreflect.EnumType {
	return &file_schema_v1_records_proto_enumTypes[0]
}

func (x Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Priority.Descriptor instead.
func (Priority) EnumDescriptor() ([]byte, []int) {
	return file_schema_v1_records_proto_rawDescGZIP(), []int{0}
}

type ProbeType int32

const (
	ProbeType_PROBE_TYPE_UNSPECIFIED ProbeType = 0
	ProbeType_PROBE_TYPE_HTTP        ProbeType = 1
	ProbeType_PROBE_TYPE_TCP         ProbeType = 2
	ProbeType_PROBE_TYPE_EXEC        ProbeType = 3
)

// Enum value maps for ProbeType.
var (
	ProbeType_name = map[int32]string{
		0: "PROBE_TYPE_UNSPECIFIED",
		1: "PROBE_TYPE_HTTP",
		2: "PROBE_TYPE_TCP",
		3: "PROBE_TYPE_EXEC",
	}
	ProbeType_value = map[string]int32{
		"PROBE_TYPE_UNSPECIFIED": 0,
		"PROBE_TYPE_HTTP":        1,
		"PROBE_TYPE_TCP":         2,
		"PROBE_TYPE_EXEC":        3,
	}
)

func (x ProbeType) Enum() *ProbeType {
	p := new(ProbeType)
	*p = x
	return p
}

func (x ProbeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProbeType) Descriptor() protoreflect.EnumDescriptor {
	return file_schema_v1_records_proto_enumTypes[1].Descriptor()
}

func (ProbeType) Type() protoreflect.EnumType {
	return &file_schema_v1_records_proto_enumTypes[1]
}

func (x ProbeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProbeType.Descriptor instead.
func (ProbeType) EnumDescriptor() ([]byte, []int) {
	return file_schema_v1_records_proto_rawDescGZIP(), []int{1}
}

type IncidentState int32

const (
	IncidentState_INCIDENT_STATE_UNSPECIFIED IncidentState = 0
	IncidentState_INCIDENT_STATE_OPEN        IncidentState = 1
	IncidentState_INCIDENT_STATE_RESOLVED    IncidentState = 2
	IncidentState_INCIDENT_STATE_ESCALATED   IncidentState = 3
)

// Enum value maps for IncidentState.
var (
	IncidentState_name = map[int32]string{
		0: "INCIDENT_STATE_UNSPECIFIED",
		1: "INCIDENT_STATE_OPEN",
		2: "INCIDENT_STATE_RESOLVED",
		3: "INCIDENT_STATE_ESCALATED",
	}
	IncidentState_value = map[string]int32{
		"INCIDENT_STATE_UNSPECIFIED": 0,
		"INCIDENT_STATE_OPEN":        1,
		"INCIDENT_STATE_RESOLVED":    2,
		"INCIDENT_STATE_ESCALATED":   3,
	}
)

func (x IncidentState) Enum() *IncidentState {
	p := new(IncidentState)
	*p = x
	return p
}

func (x IncidentState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IncidentState) Descriptor() protoreflect.EnumDescriptor {
	return file_schema_v1_records_proto_enumTypes[2].Descriptor()
}

func (IncidentState) Type() protoreflect.EnumType {
	return &file_schema_v1_records_proto_enumTypes[2]
}

func (x IncidentState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IncidentState.Descriptor instead.
func (IncidentState) EnumDescriptor() ([]byte, []int) {
	return file_schema_v1_records_proto_rawDescGZIP(), []int{2}
}

// Header is carried by every record.
type Header struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	NodeId string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Per-node, shared by all record types, never reused. Gaps are allowed
	// (crash between reserve and write, downsampling). (node_id, seq) is the dedupe key.
	Seq uint64 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	// Hybrid logical clock: unix milliseconds << 16 | logical counter.
	Hlc           uint64   `protobuf:"varint,3,opt,name=hlc,proto3" json:"hlc,omitempty"`
	Priority      Priority `protobuf:"varint,4,opt,name=priority,proto3,enum=schema.v1.Priority" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_schema_v1_records_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_schema_v1_records_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_schema_v1_records_proto_rawDescGZIP(), []int{0}
}

func (x *Header) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Header) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Header) GetHlc() uint64 {
	if x != nil {
		return x.Hlc
	}
	return 0
}

func (x *Header) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_PRIORITY_UNSPECIFIED
}

type Sample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *Header                `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Value         float64                `protobuf:"fixed64,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sample) Reset() {
	*x = Sample{}
	mi := &file_schema_v1_records_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sample) ProtoMessage() {}

func (x *Sample) ProtoReflect() protoreflect.Message {
	mi := &file_schema_v1_records_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sample.ProtoReflect.Descriptor instead.
func (*Sample) Descriptor() ([]byte, []int) {
	return file_schema_v1_records_proto_rawDescGZIP(), []int{1}
}

func (x *Sample) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Sample) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Sample) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Sample) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type Event struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Header *Header                `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// e.g. "probe_fail", "log_match", "alert", "container_state".
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// Service or container the event is about.
	Source        string            `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Message       string            `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Attrs         map[string]string `protobuf:"bytes,5,rep,name=attrs,proto3" json:"attrs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_schema_v1_records_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_schema_v1_records_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_schema_v1_records_proto_rawDescGZIP(), []int{2}
}

func (x *Event) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Event) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Event) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Event) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Event) GetAttrs() map[string]string {
	if x != nil {
		return x.Attrs
	}
	return nil
}

type ProbeResult struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Header *Header                `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Target string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Type   ProbeType              `protobuf:"varint,3,opt,name=type,proto3,enum=schema.v1.ProbeType" json:"type,omitempty"`
	// e.g. "http://:9090/-/healthy".
	Endpoint            string `protobuf:"bytes,4,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Ok                  bool   `protobuf:"varint,5,opt,name=ok,proto3" json:"ok,omitempty"`
	LatencyUs           uint64 `protobuf:"varint,6,opt,name=latency_us,json=latencyUs,proto3" json:"latency_us,omitempty"`
	Error               string `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	ConsecutiveFailures uint32 `protobuf:"varint,8,opt,name=consecutive_failures,json=consecutiveFailures,proto3" json:"consecutive_failures,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ProbeResult) Reset() {
	*x = ProbeResult{}
	mi := &file_schema_v1_records_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeResult) ProtoMessage() {}

func (x *ProbeResult) ProtoReflect() protoreflect.Message {
	mi := &file_schema_v1_records_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeResult.ProtoReflect.Descriptor instead.
func (*ProbeResult) Descriptor() ([]byte, []int) {
	return file_schema_v1_records_proto_rawDescGZIP(), []int{3}
}

func (x *ProbeResult) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ProbeResult) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ProbeResult) GetType() ProbeType {
	if x != nil {
		return x.Type
	}
	return ProbeType_PROBE_TYPE_UNSPECIFIED
}

func (x *ProbeResult) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *ProbeResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ProbeResult) GetLatencyUs() uint64 {
	if x != nil {
		return x.LatencyUs
	}
	return 0
}

func (x *ProbeResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ProbeResult) GetConsecutiveFailures() uint32 {
	if x != nil {
		return x.ConsecutiveFailures
	}
	return 0
}

// One record per state change; incident_id ties the versions together.
type Incident struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *Header                `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	IncidentId    string                 `protobuf:"bytes,2,opt,name=incident_id,json=incidentId,proto3" json:"incident_id,omitempty"`
	State         IncidentState          `protobuf:"varint,3,opt,name=state,proto3,enum=schema.v1.IncidentState" json:"state,omitempty"`
	Service       string                 `protobuf:"bytes,4,opt,name=service,proto3" json:"service,omitempty"`
	Summary       string                 `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	OpenedHlc     uint64                 `protobuf:"varint,6,opt,name=opened_hlc,json=openedHlc,proto3" json:"opened_hlc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Incident) Reset() {
	*x = Incident{}
	mi := &file_schema_v1_records_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Incident) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Incident) ProtoMessage() {}

func (x *Incident) ProtoReflect() protoreflect.Message {
	mi := &file_schema_v1_records_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Incident.ProtoReflect.Descriptor instead.
func (*Incident) Descriptor() ([]byte, []int) {
	return file_schema_v1_records_proto_rawDescGZIP(), []int{4}
}

func (x *Incident) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Incident) GetIncidentId() string {
	if x != nil {
		return x.IncidentId
	}
	return ""
}

func (x *Incident) GetState() IncidentState {
	if x != nil {
		return x.State
	}
	return IncidentState_INCIDENT_STATE_UNSPECIFIED
}

func (x *Incident) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Incident) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Incident) GetOpenedHlc() uint64 {
	if x != nil {
		return x.OpenedHlc
	}
	return 0
}

// Record is the unit stored in the sync spool and sent over the wire.
type Record struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*Record_Sample
	//	*Record_Event
	//	*Record_ProbeResult
	//	*Record_Incident
	Body          isRecord_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_schema_v1_records_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_schema_v1_records_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_schema_v1_records_proto_rawDescGZIP(), []int{5}
}

func (x *Record) GetBody() isRecord_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Record) GetSample() *Sample {
	if x != nil {
		if x, ok := x.Body.(*Record_Sample); ok {
			return x.Sample
		}
	}
	return nil
}

func (x *Record) GetEvent() *Event {
	if x != nil {
		if x, ok := x.Body.(*Record_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *Record) GetProbeResult() *ProbeResult {
	if x != nil {
		if x, ok := x.Body.(*Record_ProbeResult); ok {
			return x.ProbeResult
		}
	}
	return nil
}

func (x *Record) GetIncident() *Incident {
	if x != nil {
		if x, ok := x.Body.(*Record_Incident); ok {
			return x.Incident
		}
	}
	return nil
}

type isRecord_Body interface {
	isRecord_Body()
}

type Record_Sample struct {
	Sample *Sample `protobuf:"bytes,1,opt,name=sample,proto3,oneof"`
}

type Record_Event struct {
	Event *Event `protobuf:"bytes,2,opt,name=event,proto3,oneof"`
}

type Record_ProbeResult struct {
	ProbeResult *ProbeResult `protobuf:"bytes,3,opt,name=probe_result,json=probeResult,proto3,oneof"`
}

type Record_Incident struct {
	Incident *Incident `protobuf:"bytes,4,opt,name=incident,proto3,oneof"`
}

func (*Record_Sample) isRecord_Body() {}

func (*Record_Event) isRecord_Body() {}

func (*Record_ProbeResult) isRecord_Body() {}

func (*Record_Incident) isRecord_Body() {}

var File_schema_v1_records_proto protoreflect.FileDescriptor

const file_schema_v1_records_proto_rawDesc = "" +
	"\n" +
	"\x17schema/v1/records.proto\x12\tschema.v1\"v\n" +
	"\x06Header\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12\x10\n" +
	"\x03hlc\x18\x03 \x01(\x04R\x03hlc\x12/\n" +
	"\bpriority\x18\x04 \x01(\x0e2\x13.schema.v1.PriorityR\bpriority\"\xcf\x01\n" +
	"\x06Sample\x12)\n" +
	"\x06header\x18\x01 \x01(\v2\x11.schema.v1.HeaderR\x06header\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x125\n" +
	"\x06labels\x18\x03 \x03(\v2\x1d.schema.v1.Sample.LabelsEntryR\x06labels\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x01R\x05value\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe5\x01\n" +
	"\x05Event\x12)\n" +
	"\x06header\x18\x01 \x01(\v2\x11.schema.v1.HeaderR\x06header\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x121\n" +
	"\x05attrs\x18\x05 \x03(\v2\x1b.schema.v1.Event.AttrsEntryR\x05attrs\x1a8\n" +
	"\n" +
	"AttrsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8e\x02\n" +
	"\vProbeResult\x12)\n" +
	"\x06header\x18\x01 \x01(\v2\x11.schema.v1.HeaderR\x06header\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12(\n" +
	"\x04type\x18\x03 \x01(\x0e2\x14.schema.v1.ProbeTypeR\x04type\x12\x1a\n" +
	"\bendpoint\x18\x04 \x01(\tR\bendpoint\x12\x0e\n" +
	"\x02ok\x18\x05 \x01(\bR\x02ok\x12\x1d\n" +
	"\n" +
	"latency_us\x18\x06 \x01(\x04R\tlatencyUs\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\x121\n" +
	"\x14consecutive_failures\x18\b \x01(\rR\x13consecutiveFailures\"\xd9\x01\n" +
	"\bIncident\x12)\n" +
	"\x06header\x18\x01 \x01(\v2\x11.schema.v1.HeaderR\x06header\x12\x1f\n" +
	"\vincident_id\x18\x02 \x01(\tR\n" +
	"incidentId\x12.\n" +
	"\x05state\x18\x03 \x01(\x0e2\x18.schema.v1.IncidentStateR\x05state\x12\x18\n" +
	"\aservice\x18\x04 \x01(\tR\aservice\x12\x18\n" +
	"\asummary\x18\x05 \x01(\tR\asummary\x12\x1d\n" +
	"\n" +
	"opened_hlc\x18\x06 \x01(\x04R\topenedHlc\"\xd7\x01\n" +
	"\x06Record\x12+\n" +
	"\x06sample\x18\x01 \x01(\v2\x11.schema.v1.SampleH\x00R\x06sample\x12(\n" +
	"\x05event\x18\x02 \x01(\v2\x10.schema.v1.EventH\x00R\x05event\x12;\n" +
	"\fprobe_result\x18\x03 \x01(\v2\x16.schema.v1.ProbeResultH\x00R\vprobeResult\x121\n" +
	"\bincident\x18\x04 \x01(\v2\x13.schema.v1.IncidentH\x00R\bincidentB\x06\n" +
	"\x04body*y\n" +
	"\bPriority\x12\x18\n" +
	"\x14PRIORITY_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fPRIORITY_METRIC\x10\x01\x12\x12\n" +
	"\x0ePRIORITY_EVENT\x10\x02\x12\x13\n" +
	"\x0fPRIORITY_ACTION\x10\x03\x12\x15\n" +
	"\x11PRIORITY_INCIDENT\x10\x04*e\n" +
	"\tProbeType\x12\x1a\n" +
	"\x16PROBE_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fPROBE_TYPE_HTTP\x10\x01\x12\x12\n" +
	"\x0ePROBE_TYPE_TCP\x10\x02\x12\x13\n" +
	"\x0fPROBE_TYPE_EXEC\x10\x03*\x83\x01\n" +
	"\rIncidentState\x12\x1e\n" +
	"\x1aINCIDENT_STATE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13INCIDENT_STATE_OPEN\x10\x01\x12\x1b\n" +
	"\x17INCIDENT_STATE_RESOLVED\x10\x02\x12\x1c\n" +
	"\x18INCIDENT_STATE_ESCALATED\x10\x03B:Z8github.com/Shreyansh-Kanojiaa/theseus/schema/v1;schemav1b\x06proto3"

var (
	file_schema_v1_records_proto_rawDescOnce sync.Once
	file_schema_v1_records_proto_rawDescData []byte
)

func file_schema_v1_records_proto_rawDescGZIP() []byte {
	file_schema_v1_records_proto_rawDescOnce.Do(func() {
		file_schema_v1_records_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schema_v1_records_proto_rawDesc), len(file_schema_v1_records_proto_rawDesc)))
	})
	return file_schema_v1_records_proto_rawDescData
}

var file_schema_v1_records_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_schema_v1_records_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_schema_v1_records_proto_goTypes = []any{
	(Priority)(0),       // 0: schema.v1.Priority
	(ProbeType)(0),      // 1: schema.v1.ProbeType
	(IncidentState)(0),  // 2: schema.v1.IncidentState
	(*Header)(nil),      // 3: schema.v1.Header
	(*Sample)(nil),      // 4: schema.v1.Sample
	(*Event)(nil),       // 5: schema.v1.Event
	(*ProbeResult)(nil), // 6: schema.v1.ProbeResult
	(*Incident)(nil),    // 7: schema.v1.Incident
	(*Record)(nil),      // 8: schema.v1.Record
	nil,                 // 9: schema.v1.Sample.LabelsEntry
	nil,                 // 10: schema.v1.Event.AttrsEntry
}
var file_schema_v1_records_proto_depIdxs = []int32{
	0,  // 0: schema.v1.Header.priority:type_name -> schema.v1.Priority
	3,  // 1: schema.v1.Sample.header:type_name -> schema.v1.Header
	9,  // 2: schema.v1.Sample.labels:type_name -> schema.v1.Sample.LabelsEntry
	3,  // 3: schema.v1.Event.header:type_name -> schema.v1.Header
	10, // 4: schema.v1.Event.attrs:type_name -> schema.v1.Event.AttrsEntry
	3,  // 5: schema.v1.ProbeResult.header:type_name -> schema.v1.Header
	1,  // 6: schema.v1.ProbeResult.type:type_name -> schema.v1.ProbeType
	3,  // 7: schema.v1.Incident.header:type_name -> schema.v1.Header
	2,  // 8: schema.v1.Incident.state:type_name -> schema.v1.IncidentState
	4,  // 9: schema.v1.Record.sample:type_name -> schema.v1.Sample
	5,  // 10: schema.v1.Record.event:type_name -> schema.v1.Event
	6,  // 11: schema.v1.Record.probe_result:type_name -> schema.v1.ProbeResult
	7,  // 12: schema.v1.Record.incident:type_name -> schema.v1.Incident
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_schema_v1_records_proto_init() }
func file_schema_v1_records_proto_init() {
	if File_schema_v1_records_proto != nil {
		return
	}
	file_schema_v1_records_proto_msgTypes[5].OneofWrappers = []any{
		(*Record_Sample)(nil),
		(*Record_Event)(nil),
		(*Record_ProbeResult)(nil),
		(*Record_Incident)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schema_v1_records_proto_rawDesc), len(file_schema_v1_records_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schema_v1_records_proto_goTypes,
		DependencyIndexes: file_schema_v1_records_proto_depIdxs,
		EnumInfos:         file_schema_v1_records_proto_enumTypes,
		MessageInfos:      file_schema_v1_records_proto_msgTypes,
	}.Build()
	File_schema_v1_records_proto = out.File
	file_schema_v1_records_proto_goTypes = nil
	file_schema_v1_records_proto_depIdxs = nil
}
