// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: schema/v1/sync.proto

package schemav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*Record              `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadRequest) Reset() {
	*x = UploadRequest{}
	mi := &file_schema_v1_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRequest) ProtoMessage() {}

func (x *UploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schema_v1_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRequest.ProtoReflect.Descriptor instead.
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return file_schema_v1_sync_proto_rawDescGZIP(), []int{0}
}

func (x *UploadRequest) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

type UploadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Records in the upload, new ones stored, and ones the control plane already held.
	Received      uint64 `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	Stored        uint64 `protobuf:"varint,2,opt,name=stored,proto3" json:"stored,omitempty"`
	Duplicates    uint64 `protobuf:"varint,3,opt,name=duplicates,proto3" json:"duplicates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResponse) Reset() {
	*x = UploadResponse{}
	mi := &file_schema_v1_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResponse) ProtoMessage() {}

func (x *UploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schema_v1_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResponse.ProtoReflect.Descriptor instead.
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return file_schema_v1_sync_proto_rawDescGZIP(), []int{1}
}

func (x *UploadResponse) GetReceived() uint64 {
	if x != nil {
		return x.Received
	}
	return 0
}

func (x *UploadResponse) GetStored() uint64 {
	if x != nil {
		return x.Stored
	}
	return 0
}

func (x *UploadResponse) GetDuplicates() uint64 {
	if x != nil {
		return x.Duplicates
	}
	return 0
}

var File_schema_v1_sync_proto protoreflect.FileDescriptor

const file_schema_v1_sync_proto_rawDesc = "" +
	"\n" +
	"\x14schema/v1/sync.proto\x12\tschema.v1\x1a\x17schema/v1/records.proto\"<\n" +
	"\rUploadRequest\x12+\n" +
	"\arecords\x18\x01 \x03(\v2\x11.schema.v1.RecordR\arecords\"d\n" +
	"\x0eUploadResponse\x12\x1a\n" +
	"\breceived\x18\x01 \x01(\x04R\breceived\x12\x16\n" +
	"\x06stored\x18\x02 \x01(\x04R\x06stored\x12\x1e\n" +
	"\n" +
	"duplicates\x18\x03 \x01(\x04R\n" +
	"duplicates2N\n" +
	"\vSyncService\x12?\n" +
	"\x06Upload\x12\x18.schema.v1.UploadRequest\x1a\x19.schema.v1.UploadResponse(\x01B:Z8github.com/Shreyansh-Kanojiaa/theseus/schema/v1;schemav1b\x06proto3"

var (
	file_schema_v1_sync_proto_rawDescOnce sync.Once
	file_schema_v1_sync_proto_rawDescData []byte
)

func file_schema_v1_sync_proto_rawDescGZIP() []byte {
	file_schema_v1_sync_proto_rawDescOnce.Do(func() {
		file_schema_v1_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schema_v1_sync_proto_rawDesc), len(file_schema_v1_sync_proto_rawDesc)))
	})
	return file_schema_v1_sync_proto_rawDescData
}

var file_schema_v1_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_schema_v1_sync_proto_goTypes = []any{
	(*UploadRequest)(nil),  // 0: schema.v1.UploadRequest
	(*UploadResponse)(nil), // 1: schema.v1.UploadResponse
	(*Record)(nil),         // 2: schema.v1.Record
}
var file_schema_v1_sync_proto_depIdxs = []int32{
	2, // 0: schema.v1.UploadRequest.records:type_name -> schema.v1.Record
	0, // 1: schema.v1.SyncService.Upload:input_type -> schema.v1.UploadRequest
	1, // 2: schema.v1.SyncService.Upload:output_type -> schema.v1.UploadResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_schema_v1_sync_proto_init() }
func file_schema_v1_sync_proto_init() {
	if File_schema_v1_sync_proto != nil {
		return
	}
	file_schema_v1_records_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schema_v1_sync_proto_rawDesc), len(file_schema_v1_sync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_schema_v1_sync_proto_goTypes,
		DependencyIndexes: file_schema_v1_sync_proto_depIdxs,
		MessageInfos:      file_schema_v1_sync_proto_msgTypes,
	}.Build()
	File_schema_v1_sync_proto = out.File
	file_schema_v1_sync_proto_goTypes = nil
	file_schema_v1_sync_proto_depIdxs = nil
}
